"""Generates 01_flood_from_space.ipynb — kept as a script so the notebook
stays reviewable in git and can be regenerated after edits."""
import json
from pathlib import Path

def md(*lines): return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}
def code(*lines): return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": list(lines)}

cells = [
md("# หาน้ำท่วมจากดาวเทียม ใน 1 ชั่วโมง\n",
   "\n",
   "**ไม่ต้องสมัครอะไรเลย ไม่ต้องมีบัตรเครดิต ไม่ต้องลงโปรแกรม**\n",
   "\n",
   "จบบทนี้คุณจะได้แผนที่น้ำท่วมของจริงจากดาวเทียม Sentinel-1 พร้อมตัวเลขว่ากี่ไร่\n",
   "\n",
   "---\n",
   "\n",
   "### ทำไมต้องเรดาร์ ไม่ใช่ภาพถ่ายธรรมดา\n",
   "\n",
   "น้ำท่วมมากับเมฆเสมอ ภาพถ่ายดาวเทียมแบบที่ตาเห็น (เช่น Landsat, Sentinel-2)\n",
   "จึงมักได้แต่เมฆขาวๆ ในวันที่เราต้องการดูที่สุด\n",
   "\n",
   "**เรดาร์ (SAR) ทะลุเมฆได้ และทำงานกลางคืน** เพราะยิงคลื่นลงไปเองแล้ววัดสิ่งที่สะท้อนกลับ\n",
   "\n",
   "หลักการง่ายมาก:\n",
   "- **ผิวน้ำเรียบ** → คลื่นสะท้อนออกไปทางอื่น ไม่กลับมาหาดาวเทียม → **ภาพออกมาดำ**\n",
   "- **พื้นดิน ต้นไม้ บ้านเรือน** → ผิวขรุขระ สะท้อนกลับมามาก → **ภาพออกมาสว่าง**\n",
   "\n",
   "ที่ไหนเคยสว่างแล้วจู่ๆ กลายเป็นดำ = น้ำเพิ่งมาท่วม"),

md("## เตรียมเครื่องมือ\n",
   "\n",
   "กดปุ่ม ▶ ทางซ้ายของช่องด้านล่าง (ใช้เวลาราว 1 นาที)"),
code("!pip install -q rasterio shapely folium\n",
     "print('พร้อมแล้ว')"),

md("## 1. หาว่าดาวเทียมบินผ่านที่ไหนบ้าง\n",
   "\n",
   "หน่วยงาน **Copernicus EMS** ของสหภาพยุโรปประมวลผลภาพเรดาร์ทั้งโลกให้ฟรี\n",
   "แล้วบอกว่าตรงไหนมีน้ำท่วม เราแค่ไปขอมาใช้ผ่านระบบค้นหาที่ชื่อ **STAC**\n",
   "\n",
   "STAC เปรียบเหมือนแคตตาล็อกสินค้าของข้อมูลดาวเทียม — บอกพิกัด บอกวันที่ แล้วมันคืนรายการภาพให้"),
code("import json, urllib.request, ssl, certifi\n",
     "from datetime import datetime, timedelta, timezone\n",
     "\n",
     "# พื้นที่ศึกษา: ลุ่มเจ้าพระยา (ชัยนาท สิงห์บุรี อ่างทอง)\n",
     "# ลองเปลี่ยนเป็นจังหวัดของคุณได้ตอนท้ายบท\n",
     "BBOX = [99.8, 14.6, 100.5, 15.3]   # [ตะวันตก, ใต้, ตะวันออก, เหนือ]\n",
     "DAYS_BACK = 14                      # ย้อนหลังกี่วัน\n",
     "\n",
     "ctx = ssl.create_default_context(cafile=certifi.where())\n",
     "end = datetime.now(timezone.utc)\n",
     "start = end - timedelta(days=DAYS_BACK)\n",
     "\n",
     "body = {\n",
     "    'collections': ['GFM'],\n",
     "    'bbox': BBOX,\n",
     "    'datetime': f'{start:%Y-%m-%dT%H:%M:%SZ}/{end:%Y-%m-%dT%H:%M:%SZ}',\n",
     "    'limit': 20,\n",
     "}\n",
     "req = urllib.request.Request(\n",
     "    'https://stac.eodc.eu/api/v1/search',\n",
     "    data=json.dumps(body).encode(),\n",
     "    headers={'Content-Type': 'application/json'},\n",
     ")\n",
     "items = json.load(urllib.request.urlopen(req, context=ctx, timeout=120))['features']\n",
     "\n",
     "print(f'ดาวเทียมบินผ่านพื้นที่นี้ {len(items)} รอบ ใน {DAYS_BACK} วันที่ผ่านมา\\n')\n",
     "for it in items[:5]:\n",
     "    print(' ', it['properties']['datetime'][:16].replace('T', ' '), 'UTC')"),

md("**สังเกต**: ดาวเทียมไม่ได้บินผ่านทุกวัน — Sentinel-1 วนกลับมาที่เดิมทุก 1-3 วัน\n",
   "นี่คือข้อจำกัดสำคัญที่ต้องบอกผู้ใช้เสมอ ว่าภาพที่เห็นอาจเก่าถึง 2-3 วัน"),

md("## 2. โหลดผลวิเคราะห์น้ำท่วมมาดู\n",
   "\n",
   "**ข้อควรระวังที่คนมักพลาด**: ดาวเทียมถ่ายเป็น *แถบ* กว้างราว 250 กม.\n",
   "รอบล่าสุดอาจพาดไม่ถึงพื้นที่เรา แม้ระบบค้นหาจะบอกว่า 'เกี่ยวข้อง'\n",
   "เพราะแผ่นข้อมูลใหญ่กว่าแถบที่ถ่ายจริง\n",
   "\n",
   "โค้ดข้างล่างจึงไล่ดูทีละรอบ จนเจอรอบที่ถ่ายครอบพื้นที่เราจริงๆ\n",
   "\n",
   "แต่ละรอบบินให้ไฟล์ภาพมาหลายแบบ เราสนใจอันชื่อ `ensemble_flood_extent`\n",
   "ซึ่งเป็นภาพที่ทุก pixel บอกว่า:\n",
   "\n",
   "| ค่า | ความหมาย |\n",
   "|---|---|\n",
   "| 0 | ดาวเทียมเห็น และ**ไม่มี**น้ำท่วม |\n",
   "| 1 | ดาวเทียมเห็น และ**มี**น้ำท่วม |\n",
   "| 255 | ดาวเทียมไม่ได้ถ่ายตรงนี้ |\n",
   "\n",
   "แต่ละ pixel กว้าง 20 เมตร"),
code("import rasterio\n",
     "import numpy as np\n",
     "from rasterio.windows import from_bounds\n",
     "from rasterio.warp import transform_bounds\n",
     "\n",
     "def read_flood(item):\n",
     "    \"\"\"อ่านเฉพาะกรอบพื้นที่เรา (แผ่นเต็ม 15000x15000 pixel ใหญ่เกินจะโหลดหมด)\"\"\"\n",
     "    url = item['assets']['ensemble_flood_extent']['href']\n",
     "    with rasterio.open(f'/vsicurl/{url}') as src:\n",
     "        b = transform_bounds('EPSG:4326', src.crs, *BBOX)\n",
     "        win = from_bounds(*b, transform=src.transform)\n",
     "        return src.read(1, window=win), src.window_transform(win), src.crs\n",
     "\n",
     "flood = win_transform = crs = item = None\n",
     "for cand in items:\n",
     "    arr, tr, c = read_flood(cand)\n",
     "    observed = (arr != 255).sum()          # 255 = ดาวเทียมไม่ได้ถ่ายตรงนี้\n",
     "    when = cand['properties']['datetime'][:16].replace('T', ' ')\n",
     "    covered = observed / arr.size * 100\n",
     "    print(f\"{when}  ถ่ายครอบพื้นที่เรา {covered:5.1f}%\")\n",
     "    if covered > 50 and flood is None:      # เจอรอบที่ใช้ได้แล้ว\n",
     "        flood, win_transform, crs, item = arr, tr, c, cand\n",
     "\n",
     "if flood is None:\n",
     "    raise SystemExit('ไม่มีรอบไหนถ่ายครอบพื้นที่นี้ — ลองเพิ่ม DAYS_BACK')\n",
     "\n",
     "print(f\"\\nเลือกใช้รอบ {item['properties']['datetime'][:16].replace('T', ' ')} UTC\")\n",
     "print(f'ภาพขนาด {flood.shape[1]} x {flood.shape[0]} pixel\\n')\n",
     "for v, n in zip(*np.unique(flood, return_counts=True)):\n",
     "    meaning = {0: 'ไม่ท่วม', 1: 'น้ำท่วม', 255: 'ไม่ได้ถ่าย'}.get(int(v), '?')\n",
     "    print(f'  ค่า {int(v):3d} = {meaning:12s} {int(n):>10,} pixel')"),

md("## 3. ดูด้วยตา\n",
   "\n",
   "ตัวเลขอย่างเดียวไม่พอ ต้องเห็นภาพว่าน้ำอยู่ตรงไหน"),
code("import matplotlib.pyplot as plt\n",
     "\n",
     "fig, ax = plt.subplots(figsize=(9, 9))\n",
     "ax.imshow(np.where(flood == 255, np.nan, flood), cmap='Blues', vmin=0, vmax=1)\n",
     "ax.set_title(f\"น้ำท่วมที่ตรวจพบ — {item['properties']['datetime'][:10]}\", fontsize=13)\n",
     "ax.axis('off')\n",
     "plt.show()"),

md("## 4. ปัญหาที่ต้องระวัง: แม่น้ำก็เป็นน้ำ\n",
   "\n",
   "จุดสีน้ำเงินบางส่วนคือ**แม่น้ำกับบึงที่มีน้ำอยู่แล้วตลอดปี** ไม่ใช่น้ำท่วม\n",
   "ถ้านับรวมไปด้วย ตัวเลขพื้นที่จะเกินจริง\n",
   "\n",
   "วิธีแก้: ใช้ข้อมูล **JRC Global Surface Water** ซึ่งบอกว่าแต่ละจุดบนโลก\n",
   "มีน้ำกี่เดือนต่อปี (จากภาพย้อนหลัง 40 ปี) แล้วลบจุดที่ปกติก็มีน้ำออก\n",
   "\n",
   "> นี่คือบทเรียนสำคัญของงานข้อมูลดาวเทียม: **ผลลัพธ์ดิบมักต้องกรองด้วยความรู้บริบทเสมอ**"),
code("from rasterio.warp import Resampling, reproject\n",
     "\n",
     "# ข้อมูลนี้แบ่งเป็นแผ่นละ 10 องศา — เลือกแผ่นที่ครอบพื้นที่เรา\n",
     "JRC = ('https://storage.googleapis.com/global-surface-water/downloads2021/'\n",
     "       'seasonality/seasonality_100E_20Nv1_4_2021.tif')\n",
     "\n",
     "water_months = np.zeros(flood.shape, dtype='uint8')\n",
     "with rasterio.open(f'/vsicurl/{JRC}') as jrc:\n",
     "    reproject(\n",
     "        source=rasterio.band(jrc, 1), destination=water_months,\n",
     "        dst_transform=win_transform, dst_crs=crs,\n",
     "        resampling=Resampling.max,   # เก็บค่าสูงสุด กันแม่น้ำแคบหลุด\n",
     "    )\n",
     "\n",
     "PERMANENT = 6   # มีน้ำตั้งแต่ 6 เดือน/ปีขึ้นไป = แหล่งน้ำ ไม่ใช่น้ำท่วม\n",
     "is_flood = flood == 1\n",
     "is_water_body = water_months >= PERMANENT\n",
     "real_flood = is_flood & ~is_water_body\n",
     "\n",
     "removed = int((is_flood & is_water_body).sum())\n",
     "print(f'ตรวจพบทั้งหมด      {int(is_flood.sum()):>9,} pixel')\n",
     "print(f'เป็นแหล่งน้ำถาวร   {removed:>9,} pixel  ({removed/max(is_flood.sum(),1)*100:.0f}%)')\n",
     "print(f'เป็นน้ำท่วมจริง    {int(real_flood.sum()):>9,} pixel')"),

md("## 5. แปลงเป็นตัวเลขที่คนไทยเข้าใจ\n",
   "\n",
   "pixel ละ 20×20 เมตร = 400 ตารางเมตร และ 1 ไร่ = 1,600 ตารางเมตร"),
code("px_m2 = 400\n",
     "rai = real_flood.sum() * px_m2 / 1600\n",
     "km2 = real_flood.sum() * px_m2 / 1_000_000\n",
     "\n",
     "print(f'พื้นที่น้ำท่วม: {rai:,.0f} ไร่  ({km2:.1f} ตร.กม.)')\n",
     "print(f'เทียบเท่าสนามฟุตบอลราว {rai*1600/7140:,.0f} สนาม')"),

md("## 6. วางบนแผนที่จริง\n",
   "\n",
   "ตัวเลขกับภาพขาวดำยังบอกไม่ได้ว่า *หมู่บ้านไหน* เดือดร้อน — ต้องวางบนแผนที่"),
code("import folium\n",
     "from rasterio.warp import calculate_default_transform\n",
     "\n",
     "# แปลงภาพเป็นพิกัดละติจูด/ลองจิจูดเพื่อวางบนแผนที่\n",
     "dst_crs = 'EPSG:4326'\n",
     "t, w, h = calculate_default_transform(crs, dst_crs, flood.shape[1], flood.shape[0],\n",
     "                                      *rasterio.transform.array_bounds(*flood.shape, win_transform))\n",
     "wgs = np.zeros((h, w), dtype='uint8')\n",
     "reproject(source=real_flood.astype('uint8'), destination=wgs,\n",
     "          src_transform=win_transform, src_crs=crs,\n",
     "          dst_transform=t, dst_crs=dst_crs, resampling=Resampling.max)\n",
     "\n",
     "west, south, east, north = rasterio.transform.array_bounds(h, w, t)\n",
     "rgba = np.zeros((h, w, 4), dtype='uint8')\n",
     "rgba[..., 2] = 255                      # สีน้ำเงิน\n",
     "rgba[..., 1] = 200\n",
     "rgba[..., 3] = np.where(wgs > 0, 190, 0)\n",
     "\n",
     "m = folium.Map(location=[(south+north)/2, (west+east)/2], zoom_start=10,\n",
     "               tiles='CartoDB positron')\n",
     "folium.raster_layers.ImageOverlay(rgba, [[south, west], [north, east]], opacity=0.85).add_to(m)\n",
     "m"),

md("---\n",
   "\n",
   "## ลองต่อเอง\n",
   "\n",
   "1. **เปลี่ยนพื้นที่** — แก้ `BBOX` ในข้อ 1 เป็นจังหวัดของคุณ\n",
   "   (หาพิกัดได้จาก Google Maps คลิกขวาบนแผนที่)\n",
   "2. **เปลี่ยนช่วงเวลา** — แก้ `DAYS_BACK` เป็น 30 แล้วดูว่าเจอกี่รอบบิน\n",
   "3. **ลองปรับเกณฑ์แหล่งน้ำ** — เปลี่ยน `PERMANENT` จาก 6 เป็น 3 หรือ 10\n",
   "   แล้วดูว่าตัวเลขพื้นที่เปลี่ยนไปแค่ไหน คุณคิดว่าเลขไหนถูกต้อง เพราะอะไร\n",
   "\n",
   "## คำถามชวนคิด\n",
   "\n",
   "- ถ้าดาวเทียมบินผ่านทุก 1-3 วัน แล้วน้ำป่าที่มาแล้วลดใน 6 ชั่วโมง เราจะจับได้ไหม\n",
   "- SAR มองไม่เห็นน้ำใต้ต้นไม้หนาทึบและในเมืองที่ตึกสูง — จะรู้ได้อย่างไรว่าตรงนั้นท่วมหรือไม่\n",
   "- ตัวเลข 'กี่ไร่' ที่เราคำนวณ เอาไปใช้ชดเชยเกษตรกรได้เลยหรือไม่ ต้องระวังอะไร\n",
   "\n",
   "## แหล่งข้อมูลที่ใช้ (ฟรีทั้งหมด)\n",
   "\n",
   "| ข้อมูล | ที่มา | ต้องสมัคร |\n",
   "|---|---|---|\n",
   "| น้ำท่วมจากเรดาร์ | Copernicus EMS Global Flood Monitoring | ไม่ต้อง |\n",
   "| แหล่งน้ำถาวร | JRC Global Surface Water | ไม่ต้อง |\n",
   "| แผนที่ฐาน | CartoDB | ไม่ต้อง |"),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
        "colab": {"provenance": []},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}
Path("01_flood_from_space.ipynb").write_text(json.dumps(nb, ensure_ascii=False, indent=1))
print(f"wrote 01_flood_from_space.ipynb — {len(cells)} cells")
